In [4]:
import numpy as np 


In [24]:
import numpy as np

# Bạn truyền trực tiếp các con số kích thước vào hàm
data = np.random.rand(6, 6, 3)



In [27]:
print ( data) 
print (data.shape[1] )

[[[0.27252367 0.91587868 0.68442952]
  [0.08744439 0.74962111 0.55768268]
  [0.61931449 0.48049759 0.46619454]
  [0.91194064 0.83683264 0.05517798]
  [0.34923374 0.37720826 0.14587771]
  [0.14334156 0.67742601 0.52568398]]

 [[0.16955699 0.50973647 0.92629497]
  [0.71833586 0.27111257 0.50910731]
  [0.61113084 0.17380249 0.30783447]
  [0.17491816 0.72470333 0.47559475]
  [0.43733886 0.24324478 0.84042553]
  [0.64958623 0.56584294 0.02551537]]

 [[0.6487768  0.92946612 0.75731192]
  [0.21063405 0.4532358  0.54935277]
  [0.89395619 0.54478931 0.90783466]
  [0.30456787 0.50530508 0.2318883 ]
  [0.69789201 0.19547543 0.32503144]
  [0.4558359  0.91903966 0.63213831]]

 [[0.66018599 0.95950571 0.46054675]
  [0.2200339  0.24972071 0.83700096]
  [0.42426942 0.55189795 0.88254974]
  [0.4412238  0.80428623 0.40329205]
  [0.7107635  0.44493201 0.07943248]
  [0.99292381 0.70969589 0.32693219]]

 [[0.85876028 0.79582424 0.55406895]
  [0.64699514 0.34444483 0.30352893]
  [0.95033019 0.34362602 0.554

In [28]:
a= np.random.randint(1)

In [29]:
a 

0

TEST CNN3D LAYER 


In [30]:
from CNN_EDA import CNN3D

In [31]:
a = np.random.rand(6,6,3)


In [32]:
conv3d = CNN3D (input_channel = 3 ,  output_channel = 0 , kernel =3 , Stride= 1  , Padding = 0 )

In [33]:
a_conv3d = conv3d(a)

TypeError: 'CNN3D' object is not callable